services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    env_file: .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .
    container_name: backend
    restart: always
    # depends_on:
    #   - db
    env_file: .env
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - MYSQL_URL=${MYSQL_URL}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - DOMAIN_URL=${DOMAIN_URL}
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads

volumes:
  mysql_data:
